
package fr.afcepf.atod19.soa.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculTva", targetNamespace = "http://service.soa.atod19.afcepf.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculTva {


    /**
     * 
     * @param taux
     * @param ht
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ttc", targetNamespace = "http://service.soa.atod19.afcepf.fr/", className = "fr.afcepf.atod19.soa.service.Ttc")
    @ResponseWrapper(localName = "ttcResponse", targetNamespace = "http://service.soa.atod19.afcepf.fr/", className = "fr.afcepf.atod19.soa.service.TtcResponse")
    public double ttc(
        @WebParam(name = "ht", targetNamespace = "")
        double ht,
        @WebParam(name = "taux", targetNamespace = "")
        double taux);

    /**
     * 
     * @param taux
     * @param ht
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "tva", targetNamespace = "http://service.soa.atod19.afcepf.fr/", className = "fr.afcepf.atod19.soa.service.Tva")
    @ResponseWrapper(localName = "tvaResponse", targetNamespace = "http://service.soa.atod19.afcepf.fr/", className = "fr.afcepf.atod19.soa.service.TvaResponse")
    public double tva(
        @WebParam(name = "ht", targetNamespace = "")
        double ht,
        @WebParam(name = "taux", targetNamespace = "")
        double taux);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAuteur", targetNamespace = "http://service.soa.atod19.afcepf.fr/", className = "fr.afcepf.atod19.soa.service.GetAuteur")
    @ResponseWrapper(localName = "getAuteurResponse", targetNamespace = "http://service.soa.atod19.afcepf.fr/", className = "fr.afcepf.atod19.soa.service.GetAuteurResponse")
    public String getAuteur();

}
